Initial release
webmd-health-services/YouTrackAutomation pull request #1
Opened 2024-08-05 22:47 UTC by CameronSWilliamson

Adding the following functions:

* `Get-YTIssue`
* `Get-YTProject`
* `Invoke-YTRestMethod`
* `New-YTIssue`
* `New-YTProject`
* `New-YTSession`

2024-08-22 19:05 UTC, splatteredbits requested changes

2024-08-22 19:05 UTC, splatteredbits commented on Tests/Get-YTProject.Tests.ps1
> +        ThenProjectsReturned -GreaterThanEqual 1
I would combine the two `ThenProject*` functions into a single `ThenReturns` function:

```powershell
ThenReturns -Count 2
ThenReturns -ProjectWithShortName 'DEMO'
```

2024-08-22 19:05 UTC, splatteredbits commented on Tests/Get-YTProject.Tests.ps1
> +        ThenProjectWithShortName -ShortName 'DEMO'
Assert both projects that get returned.

2024-08-22 19:05 UTC, splatteredbits commented on Tests/Get-YTProject.Tests.ps1
> +        ThenProjectsReturned -GreaterThanEqual 1
Don't use `GreaterThanEqual`. Use an exact count. If you use greater than or equal to, if the API returns more than expected, tests will still pass.

2024-08-22 19:05 UTC, splatteredbits commented on Tests/Invoke-YTRestMethod.Tests.ps1
> +    It 'should always make GET requests' {
Add a test that actually calls a rest method.

2024-08-22 19:05 UTC, splatteredbits commented on Tests/New-YTIssue.Tests.ps1
> +        GivenSummary 'First YTAutomation Issue'
Remove tall these `Given` functions. `Given` functions should, in general, be used to setup the state of the system. These are better as parameters on `WhenCreatingIssue`.

```powershell
WhenCreatingIssue -WithSummary '' -WithDescription '' -InProject ''
```

2024-08-22 19:05 UTC, splatteredbits commented on Tests/New-YTIssue.Tests.ps1
> +        ThenIssue
Add parameter users have to pass to assert the issue:

```powershell
ThenIssue -Created -WithSummary '' -WithDescription '' -InProject ''
```

`ThenIssue` should make a call to YouTrack to get the issue.

2024-08-22 19:05 UTC, splatteredbits commented on Tests/New-YTProject.Tests.ps1
> +        WhenCreatingProject -Name 'New-YTProject Test2' -ShortName 'NYTP2' -Leader 'admin' -Template 'scrum'
Why creating two projects here?

2024-08-22 19:05 UTC, splatteredbits commented on Tests/New-YTProject.Tests.ps1
> +        { WhenCreatingProject -Name 'New-YTProject Test4' -ShortName 'NYTP4' -Leader 'admin' } | Should -Throw
Add an expected exception message so we're not silently ignoring a bug that's causing a different terminating error.

2024-08-22 19:05 UTC, splatteredbits commented on YouTrackAutomation/Functions/Get-YTIssue.ps1
> +    The `Get-YTIssue` function gets an issue from YouTrack using the issue ID or issue key. The function returns the
Add a couple sentences after the first sentence. about how to call the function, e.g. "Pass the issue ID to the `IssueID` parameter. By default *X* fields are returned. To return additional fields, pass them to the `AdditionalField` parameter."

2024-08-22 19:05 UTC, splatteredbits commented on YouTrackAutomation/Functions/Get-YTIssue.ps1
> +        [String[]] $AdditionalFields
Lint: user singular nouns for parameter names.

2024-08-22 19:05 UTC, splatteredbits commented on YouTrackAutomation/Functions/Get-YTIssue.ps1
> +    Invoke-YTRestMethod -Session $Session -Name "issues/${IssueId}?fields=$fields"
Input from user so URL encode `$fields`.

2024-08-22 19:05 UTC, splatteredbits commented on YouTrackAutomation/Functions/Get-YTProject.ps1
> +        [String] $ProjectShortName,
Lint: do not duplicate function noun in parameter names. Shorten to `ShortName`.

2024-08-22 19:05 UTC, splatteredbits commented on YouTrackAutomation/Functions/Get-YTProject.ps1
> +    The `Get-YTProject` function gets projects from YouTrack. The function returns the following fields by default:
Add a sentence or two after the first sentence decribing how to call the function: "By default, all projects are returned. To return a specific project, pass its short name to the `ShortName` parameter. Wildcards are not supported."

2024-08-22 19:05 UTC, splatteredbits commented on YouTrackAutomation/Functions/Get-YTProject.ps1
> +        [String[]] $AdditionalFields
Lint: use singular nouns for parameter names. Rename to `AdditionalField`.

2024-08-22 19:05 UTC, splatteredbits commented on YouTrackAutomation/Functions/Get-YTProject.ps1
> +    $projects = Invoke-YTRestMethod -Session $Session -Name "admin/projects?fields=$fields"
URL encode `$fields` since can come from user.

2024-08-22 19:05 UTC, splatteredbits commented on YouTrackAutomation/Functions/Get-YTProject.ps1
> +        $projects | Where-Object { $_.shortName -eq $ProjectShortName }
Lint: Prefer simplified `Where-Object` syntax: `Where-Object 'shortName' -EQ $ShortName`.

2024-08-22 19:05 UTC, splatteredbits commented on YouTrackAutomation/Functions/Get-YTProject.ps1
> +        $projects | Where-Object { $_.shortName -eq $ProjectShortName }
Lint: avoid unnecessary blocks. Add a `return` statement here, then move contents of else block out:

```powershell
if ($ShortName)
{
    return $projects | Where-Object 'shortName -EQ $ShortName
}

return $projects
```

2024-08-22 19:05 UTC, splatteredbits commented on YouTrackAutomation/Functions/Invoke-YTRestMethod.ps1
> +    name of the API endpoint to make the request to. By default, the function will use the `GET` method, but you can
Rephrse the third sentence: "By default, make the HTTP request using the HTTP `Get` method. Use the `-Method` parameter to use a different HTTP method."

2024-08-22 19:05 UTC, splatteredbits commented on YouTrackAutomation/Functions/Invoke-YTRestMethod.ps1
> +    $url = [uri]::EscapeUriString("$($Session.Url)${name}")
Don't escape here. The function has no idea what `$Name` contains. Won't you be escaping valid slashes and `?` and `&` characters? I"m surprised any request made by this function work.

2024-08-22 19:05 UTC, splatteredbits commented on YouTrackAutomation/Functions/New-YTIssue.ps1
> +    The `New-YTIssue` function creates a new issue in YouTrack. To create an issue, you must provide the project's short
Short second sentence to "Pass the short name of the project where the issue should be created to the `Project` parameter, and the..."

2024-08-22 19:05 UTC, splatteredbits commented on YouTrackAutomation/Functions/New-YTIssue.ps1
> +        [String] $Project,
We want to make as few web requests as possible, so either change this to `ProjectID` or allow users to pass a project object, short name, or ID. For the second object, change its type to `Object` then create a `Resolve-YTProject` function that handles that:

```powershell
if ($Project | Get-Member -Name 'id')
{
    return $Project.id
}

if ($Project -is [int] -or $Project -match '^\d+$' )
{
    return Get-YTProject -Session $Session -ID $Project
}

if ($Project -is [String])
{
    return Get-YTProject -Session $Session -ShortName $Project
}

Write-Error "Failed to resolve project ""${Project}"": expected an object with an `id` property, an integer ID, or a project short name."
```

2024-08-22 19:05 UTC, splatteredbits commented on YouTrackAutomation/Functions/New-YTProject.ps1
> +        [String] $Leader,
We want to make as few web requests as possible, so either change this to LeaderID or allow users to pass a leader object, short name, or ID. For the second object, change its type to Object then create a Resolve-YTLeader function that handles that.

2024-08-22 19:05 UTC, splatteredbits commented on YouTrackAutomation/Functions/New-YTProject.ps1
> +        $fields += "&template=$Template"
URL encode `$Template`.

2024-08-22 19:05 UTC, splatteredbits commented on YouTrackAutomation/Functions/New-YTProject.ps1
> +    Invoke-YTRestMethod -Session $Session -Name "admin/projects?fields=$fields" -Body $body -Method Post
URL encode `$fields`.

2024-08-22 19:05 UTC, splatteredbits commented on YouTrackAutomation/YouTrackAutomation.psd1
> +    ModuleVersion = '0.1.0'
`1.0.0`.

2025-01-06 22:10 UTC, CameronSWilliamson commented on Tests/New-YTProject.Tests.ps1
> +        WhenCreatingProject -Name 'New-YTProject Test2' -ShortName 'NYTP2' -Leader 'admin' -Template 'scrum'
To test out both of the template types accessible via the API in one test.

2025-01-07 19:56 UTC, CameronSWilliamson commented on YouTrackAutomation/Functions/New-YTProject.ps1
> +        [String] $Leader,
I would agree with you except this is the only situation where the leader is used. In this case I would rather allow users to provide the leader name or ID as the same parameter and determine within this function how to proceed. If there comes a point where multiple functions require a leader then I will consider this.

2025-01-09 21:31 UTC, splatteredbits requested changes

2025-01-09 21:31 UTC, splatteredbits commented on whiskey.yml
> +- PowerShell:
Call `reset.ps1` instead.

But consider removing? Do we really need to clean up on the build server? The VM we're using is going to get reaped by AppVeyor...

2025-01-09 21:31 UTC, splatteredbits commented on init.ps1
> +$dataArchivePath = Join-Path -Path $PSScriptRoot -ChildPath 'ytconfig.zip'
Check these files into source loose, not as a ZIP file. If/when we ever need to update them, we'll have to unzip this file, update them, then zip the file back up again. It makes it hard to see what changed with the config and why.

2025-01-09 21:31 UTC, splatteredbits commented on init.ps1
> +$dataArchivePath = Join-Path -Path $PSScriptRoot -ChildPath 'ytconfig.zip'
Ideally, we just commit the files we change/care about to get YT running/working.

2025-01-09 21:31 UTC, splatteredbits commented on init.ps1
> +* Installs YouTrack to the current folder from an pre-configured YouTrack instance.
s/an/a/

2025-01-09 21:31 UTC, splatteredbits commented on init.ps1
> +* Sets up the default user account with the username 'admin' and password 'admin'.
Is there any way to generate a random password? Typically, I'll save the password to a .password file that gets ignored by source control.

2025-01-09 21:31 UTC, splatteredbits commented on YouTrackAutomation/en-US/about_YouTrackAutomation.help.txt
> +    The YouTrackAutomation PowerShell module allows for nicely interacting with YouTrack. It provides a `session` object
The about topic should contain the same information as the README.md, but formatted for PowerShell's help system.

2025-01-09 21:31 UTC, splatteredbits commented on YouTrackAutomation/YouTrackAutomation.psd1
> +    Description = 'A PowerShell wrapper for the YouTrack REST API.'
s/wrapper/module/

2025-01-09 21:31 UTC, splatteredbits commented on YouTrackAutomation/Functions/Resolve-YTProject.ps1
> +    Resolve-YTProject.ps1 -Session $session -Project 'DEMO'
This is a function, so omit the `.ps1` from the function's name.

2025-01-09 21:31 UTC, splatteredbits commented on YouTrackAutomation/Functions/Resolve-YTProject.ps1
> +    Demonstrates resolving the project id for the project with the `0-1` id.
Reword to "Demonstrates resolving the project with the id \`0-1\`."

Also, if we already have the project ID, why would we call `Resolve-YTProjectId`?

2025-01-09 21:31 UTC, splatteredbits commented on YouTrackAutomation/Functions/Resolve-YTProject.ps1
> +        # The session object for a YouTrack Session. Create a new Session using `New-YTSession`.
s/Session/session/

2025-01-09 21:31 UTC, splatteredbits commented on YouTrackAutomation/Functions/Resolve-YTProject.ps1
> +    Demonstrates resolving the project id for the project with a project object.
Reword to "Demonstrates resolving the project id using a project object."

Also, why would we need to do this? If we already have a project object, can't the caller just call `$Project.Id`?

2025-01-09 21:31 UTC, splatteredbits commented on YouTrackAutomation/Functions/Resolve-YTProject.ps1
> +    if ($Project -is [String] -and $Project -match '^\d+-\d+$')
You're testing if the project is a string twice. Instead:

```powershell
if (-not $Project -is [String])
{
    $msg = "Failed to resolve project ""${Project}"": expected an object with an `id` property, a string ID " +
           '(e.g. ''0-0''), or a project short name.'
    Write-Error $msg
    return
}

if ($Project -match '^\d+-\d+$')
{
    return $Project
}

return Get-YTProject -Session $Session -ShortName $Project | Select-Object -ExpandProperty 'id'
```

2025-01-09 21:31 UTC, splatteredbits commented on YouTrackAutomation/Functions/Remove-YTProject.ps1
> +    # $msg = $ShortName
Remove commented code.

2025-01-09 21:31 UTC, splatteredbits commented on YouTrackAutomation/Functions/Resolve-YTProject.ps1
> +    .EXAMPLE
Looks like this example might by copy/pasted from another function.

2025-01-09 21:31 UTC, splatteredbits commented on YouTrackAutomation/Functions/Remove-YTProject.ps1
> +    if ($PSCmdlet.ShouldProcess($projectId, 'Remove YouTrack Project'))
This should be built into `Invoke-YTRestMethod`. For any non-GET request, it should wrap it in an `ShouldProcess` call, so remove the `ShouldProcess` call here.

2025-01-09 21:31 UTC, splatteredbits commented on YouTrackAutomation/Functions/Remove-YTProject.ps1
> +        # The Session object for a YouTrack session. Create a new Session using `New-YTSession`.
s/Session/session/

2025-01-09 21:31 UTC, splatteredbits commented on YouTrackAutomation/Functions/New-YTSession.ps1
> +    The `New-YTSession` function creates a new YouTrack session object that can be used to interact with the YouTrack
Reword:

> The `New-YTSession` function creates a session object required by most YouTrackAutomation functions. Pass the URL to YouTrack to the `Url` parameter and your API token to the `ApiToken` parameter. The function returns an object that can be passed to all YouTrackAutomation functions' `Session` parameter.


Add some explanation of what part of the URL should be passed. Just the protocol and hostname? Any part of the path?

2025-01-09 21:31 UTC, splatteredbits commented on YouTrackAutomation/Functions/New-YTProject.ps1
> +    $fields = [Uri]::EscapeUriString($fields)
This should be `[Uri]::EscapeDataString`.

If a template is given, the `&Template=` on line 88 will get encoded to `%26Template%3D`, so you'll need to encode the fields separately from the template name,value.

2025-01-09 21:31 UTC, splatteredbits commented on YouTrackAutomation/Functions/New-YTProject.ps1
> +        name = $Name
Lint: use terminating semi-colons when using hashtable literals.

2025-01-09 21:31 UTC, splatteredbits commented on YouTrackAutomation/Functions/New-YTIssue.ps1
> +    The `New-YTIssue` function creates a new issue in YouTrack. Pass the short name of the project where the issue
Update: "Pass the project's short name, ID, or a project object where the issue should get created to the `Project` parameter."

2025-01-09 21:31 UTC, splatteredbits commented on YouTrackAutomation/Functions/New-YTIssue.ps1
> +        summary = $Summary
Lint: use semi-colons to terminate each item in a hashtable literal.

2025-01-09 21:31 UTC, splatteredbits commented on YouTrackAutomation/Functions/New-YTIssue.ps1
> +    if ($Description) {
Lint: statement open/closing braces should be on their own line.

2025-01-09 21:31 UTC, splatteredbits commented on YouTrackAutomation/Functions/Invoke-YTRestMethod.ps1
> +    The `Invoke-YTRestMethod` function invokes a REST method in YouTrack using the provided session object. Pass in the
Add information about what the body should be. JSON? Hashtable? Name/value pairs?

2025-01-09 21:31 UTC, splatteredbits commented on YouTrackAutomation/Functions/Invoke-YTRestMethod.ps1
> +        [Microsoft.PowerShell.Commands.WebRequestMethod] $Method =
Missing docs.

2025-01-09 21:31 UTC, splatteredbits commented on YouTrackAutomation/Functions/Invoke-YTRestMethod.ps1
> +        [Object] $Body
Missing docs.

2025-01-09 21:31 UTC, splatteredbits commented on YouTrackAutomation/Functions/Get-YTProject.ps1
> +    $fields = [Uri]::EscapeUriString($fields)
Should be `[Uri]::EscapeDataString($fields)`.

2025-01-09 21:31 UTC, splatteredbits commented on YouTrackAutomation/Functions/Get-YTIssue.ps1
> +    The `Get-YTIssue` function gets an issue from YouTrack using the issue ID or issue key. The function returns the
Bump.

2025-01-09 21:31 UTC, splatteredbits commented on YouTrackAutomation/Functions/Get-YTIssue.ps1
> +    $fields = [Uri]::EscapeUriString($fields)
Should be `[Uri]::EscapeDataString($fields)`.

2025-01-09 21:31 UTC, splatteredbits commented on YouTrackAutomation/Functions/New-YTProject.ps1
> +        [String[]] $AdditionalFields
Lint: parameter names should be singular.

2025-01-09 21:31 UTC, splatteredbits commented on Tests/YouTrackAutomationTestHelper/YouTrackAutomationTestHelper.psm1
> +function Remove-AllProjects
Rename to `Clear-Project`.

2025-01-09 21:31 UTC, splatteredbits commented on Tests/Invoke-YTRestMethod.Tests.ps1
> +Describe 'Invoke-YTRestMethod' {
This function is critical to everything working, so I wouldn't mock anything out. Make actual calls.

2025-01-17 19:56 UTC, CameronSWilliamson commented on YouTrackAutomation/Functions/New-YTProject.ps1
> +    $fields = [Uri]::EscapeUriString($fields)
I don't think I need to encode the template at all because I used the `[ValidateSet]` modifier on the Template parameter.

2025-01-17 20:38 UTC, CameronSWilliamson commented on YouTrackAutomation/Functions/Resolve-YTProject.ps1
> +    Demonstrates resolving the project id for the project with the `0-1` id.
I support the ID in this function so that other functions don't have to check if it is an ID before calling this function.

2025-01-17 20:39 UTC, CameronSWilliamson commented on YouTrackAutomation/Functions/Resolve-YTProject.ps1
> +    Demonstrates resolving the project id for the project with a project object.
They can, but again I'd like this function to handle all of the fetching of IDs especially in functions that can take all forms of a project.

2025-01-17 20:42 UTC, CameronSWilliamson commented on init.ps1
> +* Sets up the default user account with the username 'admin' and password 'admin'.
It doesn't look to me like that is possible. I'll keep looking though.

2025-01-24 23:56 UTC, splatteredbits commented
Please automate the download and updating of the YouTrackConfig directory. It should not be getting checked into source.

2025-01-24 23:56 UTC, splatteredbits requested changes

2025-01-24 23:56 UTC, splatteredbits commented on YouTrackAutomation/Functions/Get-YTIssue.ps1
> +    The `Get-YTIssue` function gets an issue from YouTrack using the issue ID or issue key. The function returns the
This still needs to get done.

2025-01-24 23:56 UTC, splatteredbits commented on YouTrackAutomation/Functions/Get-YTProject.ps1
> +    $fields = [Uri]::EscapeUriString($fields)
This still needs to change.

2025-01-24 23:56 UTC, splatteredbits commented on YouTrackAutomation/Functions/Invoke-YTRestMethod.ps1
> +    The `Invoke-YTRestMethod` function invokes a REST method in YouTrack using the provided session object. Pass in the
Bump.

2025-01-24 23:56 UTC, splatteredbits commented on YouTrackAutomation/Functions/New-YTProject.ps1
> +        $fields += "&template=$Template"
Bump.

2025-01-24 23:56 UTC, splatteredbits commented on YouTrackAutomation/Functions/New-YTProject.ps1
> +    $fields = [Uri]::EscapeUriString($fields)
bump.

2025-01-24 23:56 UTC, splatteredbits commented on YouTrackAutomation/Functions/Resolve-YTProject.ps1
> +    .EXAMPLE
Function name in examples is wrong.

2025-01-24 23:56 UTC, splatteredbits commented on YouTrackAutomation/Functions/Resolve-YTProject.ps1
> +    Demonstrates resolving the project id for the project with a project object.
Bump.

2025-01-29 16:56 UTC, splatteredbits approved these changes

2025-01-29 16:56 UTC, splatteredbits commented on .gitignore
> +/youtrack-2024.2.37269
Probably wildcard this to `/youtrack-*` ?

2025-01-29 16:56 UTC, splatteredbits commented on README.md
> +All commands require a `session` object in order to call them. Create a new session object using the `New-YTSession`
Remove code backticks around session.

2025-01-29 16:56 UTC, splatteredbits commented on whiskey.yml
> +- PowerShell:
@KhoiKy Bump.

2025-01-29 21:17 UTC, merged